name = "MIT16940"
uuid = "7b1a8d63-b69c-4756-8d8a-6a338d3e29c8"
authors = ["bowenszhu <bszhu@fas.harvard.edu>"]
version = "0.1.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
LaTeXStrings = "1.3"
Plots = "1.35"
julia = "1.8.2"
